#!/usr/bin/env bash
# 101-manage_my_process Bash (init) script

# Function to start manage_my_process
start_manage_my_process() {
	# Check if manage_my_process is already running
	if pgrep -x "manage_my_process" >/dev/null; then
		echo "manage_my_process is already running."
	else
		# Start manage_my_process
		./manage_my_process.sh &
		echo "$!" > /var/run/my_process.pid
		echo "manage_my_process started."
	fi
}

# Function to stop manage_my_process
stop_manage_my_process() {
	# Check if manage_my_process is running
	if pgrep -x "manage_my_process" >/dev/null; then
		# Stop manage_my_process
		pkill -f "manage_my_process"
		rm -f /var/run/my_process.pid
		echo "manage_my_process stopped."
	else
		echo "manage_my_process is not running."
	fi
}

# Function to restart manage_my_process
restart_manage_my_process() {
	stop_manage_my_process
	start_manage_my_process
	echo "manage_my_process restarted."
}

# Check argument and call respective function
case "$1" in
	start)
		start_manage_my_process
		;;
	stop)
		stop_manage_my_process
		;;
	restart)
		restart_manage_my_process
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac
