#!/usr/bin/env bash
# 101-manage_my_process Bash (init) script
# Function to start manage_my_process
start_manage_my_process() {
	# Check if manage_my_process is already running
	if [ -f /var/run/my_process.pid ]; then
		echo "manage_my_process is already running."
	else
		# Start manage_my_process
		./manage_my_process.sh & echo $! > /var/run/my_process.pid
		echo "manage_my_process started."
		# Loop indefinitely writing to file
		while true; do
			echo "I am alive!" >> /tmp/my_process
			sleep 2
		done
	fi
}

stop_manage_my_process() {
	# Check if manage_my_process is running
	if [ -f /var/run/my_process.pid ]; then
		# Stop manage_my_process
		kill $(cat /var/run/my_process.pid)
		rm /var/run/my_process.pid
		echo "manage_my_process stopped."
	else
		echo "manage_my_process is not running."
	fi
}

restart_manage_my_process() {
	# Restart manage_my_process
	stop_manage_my_process
	start_manage_my_process
	echo "manage_my_process restarted."
}

case "$1" in
	start)
		start_manage_my_process
		;;
	stop)
		stop_manage_my_process
		;;
	restart)
		restart_manage_my_process
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac
