#!/usr/bin/env bash
# Bash script that displays:
#   - To infinity and beyond indefinitely.
#   - With a sleep 2 in between each iteration.
#   - "I am invincible!!!" when receiving a SIGTERM signal.

# Function to handle SIGTERM signal
handle_sigterm() {
	echo "I am invincible!!!"
	exit 0
}

# Trap SIGTERM signal and call the handle_sigterm function
trap 'handle_sigterm' SIGTERM

# Infinite loop to display "To infinity and beyond"
while true; do
	echo "To infinity and beyond"
	sleep 2
done
