#!/usr/bin/env bash
# Bash scripts that displays:
#	to infinity and beyond indefinitely.
#	with a sleep 2 in between each iteration.
#	i am invincible!!! when receiving a SIGTERM signal

handle_sigterm()
{
	echo "I am invincible!!!"
	exit 0
}

trap ''handle_sigterm' SIGTERM

while true; do
	echo "To infinity and beyond"
	sleep 2
done
