#!/usr/bin/env bash
# manage_my_process Bash script

# Function to start manage_my_process
start_manage_my_process() {
	./101-manage_my_process start
}

# Function to stop manage_my_process
stop_manage_my_process() {
	./101-manage_my_process stop
}

# Function to restart manage_my_process
restart_manage_my_process() {
	./101-manage_my_process restart
}

# Check argument and call respective function
case "$1" in
start)
start_manage_my_process
;;
stop)
stop_manage_my_process
;;
restart)
restart_manage_my_process
;;
*)
echo "Usage: $0 {start|stop|restart}"
exit 1
;;
esac
