#!/usr/bin/env bash
# manage_my_process Bash script

start_manage_my_process() {
	# Start manage_my_process
	./101-manage_my_process start
}

stop_manage_my_process() {
	# Stop manage_my_process
	./101-manage_my_process stop
}

restart_manage_my_process() {
	./101-manage_my_process restart
}

# Check argument and call respective function
case "$1" in
	start)
		start_manage_my_process
		;;
	stop)
		stop_manage_my_process
		;;
	restart)
		restart_manage_my_process
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac
